project:
  type: website

website:
  title: "Mehak Gurnani"
  navbar: 
    pinned: true
    left:
      - text: About
        icon: person-circle
        href: index.qmd
      - text: CV
        icon: file-earmark-text-fill
        href: cv.qmd
      - text: Projects
        icon: puzzle-fill
        href: projects.qmd
        
    right: 
      - icon: github
        aria-label: GitHub
        href: https://github.com/mekgurnani
        
      - icon: linkedin
        aria-label: LinkedIn
        href: https://www.linkedin.com/in/mehak-gurnani-344kl/

        
  page-footer:
    border: true
    left: "&#169; 2025 Mehak Gurnani"
    right: |
      Made with [RStudio](https://posit.co/products/open-source/rstudio/) and [Quarto](https://quarto.org/)<br>

format:
  html:
    theme: flatly
    toc: true
    toc-depth: 4
    pagetitle: "Mehak Gurnani | {{< meta title >}}"
    page-layout: article
    smooth-scroll: true
    link-external-newwindow: true
    code-link: true
    highlight-style: a11y
    css: styles.css

editor: visual

execute:
  freeze: auto

